spring:
  application:
    name: sebastian-backend
  server:
    port: ${BACKEND_PORT}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

stripe:
  secret: ${STRIPE_SECRET}

frontend:
  url: ${FRONTEND_URL}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  observations:
    enable:
      http:
        server:
          requests: true

app:
  otel-collector-url: http://localhost:4318
